Window10: true
Android: false
IOS: false
kick-msg: "§cHola! Detectamos que usas PC y eso no sería justo para los usuarios de móvil así que por ese motivo usted no puede entrar a este servidor por favor use Android para unirse"