---
# The time used to run the clear chunk task.
# Default: 600 seconds.
clear-interval: 64

# The message used when successfully clearing the chunk.
# Use {COUNT} to get chunk count cleared.
message: "&aServer limpio eliminamos &b{COUNT}"

# The name of the world folder that you don't want to clear the chunk.
blacklisted-worlds:
  - "Lobby"
...