# Settings.yml Configuration file - CombatLogger v0.0.5
---
# Time before a player can logout safely or execute commands (in seconds)
time: 10
# Kill a player if they disconnect whilst in combat
kill-on-log: true
# List of commands players cannot execute while in combat
banned-commands:
  - tp
  - warp
  - tpa
  - spawn
  - ffa
messages:
 player-tagged: "&c- &6¡Ahora estás en combate, no te desconectes o serás castigado!"
 player-tagged-timeout: "&6- &a¡Ya no estás en combate!"
 player-run-banned-command: "&c- &6¡No puedes ejecutar este comando mientras estás en combate!"
...